CREATE TABLE  "USER_DATA" (
    "ID" NUMBER(19,0),
	"LOGIN" VARCHAR2(200) NOT NULL ENABLE,
	"PASSWORD" VARCHAR2(200) NOT NULL ENABLE,
	"ROLE" VARCHAR2(50) NOT NULL ENABLE,
	 PRIMARY KEY ("ID") ENABLE,
	 UNIQUE ("LOGIN") ENABLE
);

CREATE TABLE  "PATIENT" (
    "ID" NUMBER(19,0),
	"FULL_NAME" VARCHAR2(200) NOT NULL ENABLE,
	"BIRTHDAY" DATE NOT NULL ENABLE,
	"ADDRESS" VARCHAR2(200) NOT NULL ENABLE,
	"USER_DATA_ID" NUMBER(19,0) NOT NULL ENABLE,
	 PRIMARY KEY ("ID") ENABLE,
	 UNIQUE ("USER_DATA_ID") ENABLE
);
ALTER TABLE  "PATIENT" ADD FOREIGN KEY ("USER_DATA_ID") REFERENCES  "USER_DATA" ("ID") ON DELETE CASCADE ENABLE;

CREATE TABLE  "JOB"(
    "ID" NUMBER(19,0),
	"NAME" VARCHAR2(200) NOT NULL ENABLE,
	 PRIMARY KEY ("ID") ENABLE,
	 UNIQUE ("NAME") ENABLE
);

CREATE TABLE  "DOCTOR"(
    "ID" NUMBER(19,0),
	"FULL_NAME" VARCHAR2(200) NOT NULL ENABLE,
	"SHIFT" NUMBER(1,0) NOT NULL ENABLE,
	"JOB_ID" NUMBER(19,0) NOT NULL ENABLE,
	"USER_DATA_ID" NUMBER(19,0) NOT NULL ENABLE,
	 PRIMARY KEY ("ID") ENABLE,
	 UNIQUE ("USER_DATA_ID") ENABLE
);
ALTER TABLE  "DOCTOR" ADD FOREIGN KEY ("JOB_ID") REFERENCES  "JOB" ("ID") ON DELETE SET NULL ENABLE;
ALTER TABLE  "DOCTOR" ADD FOREIGN KEY ("USER_DATA_ID") REFERENCES  "USER_DATA" ("ID") ON DELETE CASCADE ENABLE;

CREATE TABLE  "APPOINTMENT"(
    "ID" NUMBER(19,0),
	"DATE_TIME" DATE NOT NULL ENABLE,
	"STATUS" VARCHAR2(50) NOT NULL ENABLE,
	"PATIENT_COMMENT" VARCHAR2(1000),
	"DIAGNOSIS" VARCHAR2(1000),
	"TREATMENT_MEASURES" VARCHAR2(1000),
	"PATIENT_ID" NUMBER(19,0) NOT NULL ENABLE,
	"DOCTOR_ID" NUMBER(19,0) NOT NULL ENABLE,
	 PRIMARY KEY ("ID") ENABLE,
	 UNIQUE ("DATE_TIME", "PATIENT_ID") ENABLE,
	 UNIQUE ("DATE_TIME", "DOCTOR_ID") ENABLE
);
ALTER TABLE  "APPOINTMENT" ADD FOREIGN KEY ("PATIENT_ID") REFERENCES  "PATIENT" ("ID") ON DELETE CASCADE ENABLE;
ALTER TABLE  "APPOINTMENT" ADD FOREIGN KEY ("DOCTOR_ID") REFERENCES  "DOCTOR" ("ID") ON DELETE SET NULL ENABLE;